Cafe/Controllers/DrinksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Cafe.Models;

namespace Cafe.Controllers
{
    public class DrinksController : Controller
    {
        private cofeDBEntities db = new cofeDBEntities();

        //HomePage
        public ActionResult Home()
        {
            //  return View(db.Drinks.OrderByDescending(x => x.id).ToList());
           return View( db.Drinks.OrderByDescending(x => x.id).ToList());
            //var rec = db.Drinks.Where(x => x.Dimg == admin.name).ToList().FirstOrDefault();
            //if (rec != null)
            //{
            //    Session["username"] = rec.name;
            //    Session["userId"] = rec.id;
            //    return RedirectToAction("Index", "Drinks");
            //}
            //else
            //{
            //    ViewBag.errm = "Email or password is incorrect...";
            //}
        }
        // GET: Drinks
        public ActionResult Index()
        {
            return View(db.Drinks.OrderByDescending(x => x.id).ToList());
        }

        // GET: Drinks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Drink drink = db.Drinks.Find(id);
            if (drink == null)
            {
                return HttpNotFound();
            }
            return View(drink);
        }

        // GET: Drinks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Drinks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Drink drink ,HttpPostedFileBase imgFile)
        {
            
            if (ModelState.IsValid)
            {
                string path = "";
                if (imgFile.FileName.Length > 0)
                {
                    path = "~/Images/" + Path.GetFileName(imgFile.FileName);
                    imgFile.SaveAs(Server.MapPath(path));
                }
                drink.Dimg = path;
                db.Drinks.Add(drink);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(drink);
        }

        // GET: Drinks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Drink drink = db.Drinks.Find(id);
            if (drink == null)
            {
                return HttpNotFound();
            }
            return View(drink);
        }

        // POST: Drinks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Drink drink, HttpPostedFileBase imgFile)
        {
            if (ModelState.IsValid)
            {

                string path = "";
                if (imgFile.FileName.Length > 0)
                {
                    path = "~/Images/" + Path.GetFileName(imgFile.FileName);
                    imgFile.SaveAs(Server.MapPath(path));
                }
                drink.Dimg = path;
                db.Entry(drink).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(drink);
        }

        // GET: Drinks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Drink drink = db.Drinks.Find(id);
            if (drink == null)
            {
                return HttpNotFound();
            }
            return View(drink);
        }

        // POST: Drinks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Drink drink = db.Drinks.Find(id);
            db.Drinks.Remove(drink);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Cafe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ANOOS CAFE - @ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    <style>
        #Admins {
            display: none;
        }

        h2 {
            color: white;
            font-weight: bold;
        }

        a {
            font-weight: bold;
            color: #4c70ff;
        }

            a:hover {
                color: #ffd800;
            }

        .navbar-default .navbar-nav > li > a {
            color: black
        }

        .navbar-default {
            border: 0px;
            border-radius: 0px;
        }

            .navbar-default .navbar-nav > li {
                border-radius: 58px;
            }
    </style>
    @{
        if (Session["username"] == null)
        {
            <style>
                .username, #Admins {
                    display: none;
                }
            </style>
        }
        else
        {
            <style>
                .username, #Admins {
                    display: block;
                }
            </style>
        }


        if (ViewBag.Title == "Home")
        {
            <style>
                .Home {
                    background-color: #FFD24C;
                }
            </style>
        }
        else if (ViewBag.Title == "Login")
        {
            <style>
                .Login {
                    background-color: #FFD24C;
                }
            </style>
        }
        else if (ViewBag.Title == "Index")
        {
            <style>
                .Index {
                    background-color: #FFD24C;
                }
            </style>
        }
        else if (ViewBag.Title == "AdminsIndex")
        {
            <style>
                .AdminsIndex {
                    background-color: #FFD24C;
                }
            </style>
        }
        else if (ViewBag.Title == "Location")
        {
            <style>
                .Location {
                    background-color: #FFD24C;
                }
            </style>
        }
    }
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>
<body>
    <div id="lod">
        <div class="sk-cube-grid">
            <div class="sk-cube sk-cube1"></div>
            <div class="sk-cube sk-cube2"></div>
            <div class="sk-cube sk-cube3"></div>
            <div class="sk-cube sk-cube4"></div>
            <div class="sk-cube sk-cube5"></div>
            <div class="sk-cube sk-cube6"></div>
            <div class="sk-cube sk-cube7"></div>
            <div class="sk-cube sk-cube8"></div>
            <div class="sk-cube sk-cube9"></div>
        </div>
    </div>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/Drinks/Home">
                    <img src="~/Images/anoos.jpg" height="40" width="40" style="border-radius:50% ;margin-top:-10px;z-index:2000;position:relative" />
                </a>

            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="Home"> @Html.ActionLink("Home", "Home", "Drinks")</li>
                    <li class="Login"> @Html.ActionLink("Login", "Login", "Admins")</li>
                    @*<li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About Us<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">One more separated link</a></li>
                            </ul>
                        </li>*@
                    <li class="Location"> @Html.ActionLink("Location", "Location", "Admins")</li>
                    <li id="Admins" class="Index"> @Html.ActionLink("Edit Page", "Index", "Drinks")</li>
                    @*<li id="Admins" class="Index"> @Html.ActionLink("Edit Page", "Index", "Drinks")</li>*@
                </ul>
                @*<form class="navbar-form navbar-left">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form>*@
                <ul class="nav navbar-nav navbar-right">
                    <li id="Admins" class="AdminsIndex">@Html.ActionLink("Admins", "Index", "Admins")</li>

                    <li class="dropdown" id="Admins">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@Session["username"]<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("Logout", "Logout", "Admins")</li>
                        </ul>
                    </li>

                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div id="header" class="header">ANOOS CAFE</div>
    @RenderBody()
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
  
    <script>
        var $document = $(document),
            $element = $('#header'),
            className = 'headerTop';

        $document.scroll(function () {
            if ($document.scrollTop() >= 50) {
                // user scrolled 50 pixels or more;
                // do stuff
                $element.addClass(className);
            } else {
                $element.removeClass(className);
            }
        });

        $(document).ready(function () {
            $('#lod').fadeOut(1000)
            $('.navbar-toggle').click(function () {
                $('#header').fadeToggle(0)
            });

        });
        $('.carousel').carousel({
            interval: 5000
        })
    </script>
</body>
</html>